
CONFIG_SR_POLICY_SA = """
<config>
                <drivenets-top
		        xmlns="http://drivenets.com/ns/yang/dn-top"
                xmlns:dn-protocol="http://drivenets.com/ns/yang/dn-protocol"
                xmlns:dn-segment-routing="http://drivenets.com/ns/yang/dn-segment-routing">
                      <dn-protocol:protocols>
                             <dn-segment-routing:segment-routing>
                                        <mpls>
                                                <policies>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>strict-spf</destination-algorithm>
                                                                        <policy-name>POLICY_R1</policy-name>
                                                                        <binding-sid>5000</binding-sid>
                                                                        <destination>100.4.4.4</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                        <sr-shortcuts>disabled</sr-shortcuts>
                                                                        <administrative-distance>200</administrative-distance>
                                                                        <description>ohad</description>
                                                                </config-items>
                                                                <policy-name>POLICY_R1</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH_R4</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH_R4</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>strict-spf</destination-algorithm>
                                                                        <policy-name>POLICY_R5</policy-name>
                                                                        <destination>100.5.5.5</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                        <sr-shortcuts>disabled</sr-shortcuts>
                                                                </config-items>
                                                                <policy-name>POLICY_R5</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH_R5</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH_R5</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>strict-spf</destination-algorithm>
                                                                        <policy-name>POLICY_R6</policy-name>
                                                                        <destination>100.6.6.6</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                        <sr-shortcuts>disabled</sr-shortcuts>
                                                                </config-items>
                                                                <policy-name>POLICY_R6</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH_R6</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH_R6</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>strict-spf</destination-algorithm>
                                                                        <policy-name>POLICY_R7</policy-name>
                                                                        <destination>100.7.7.7</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                        <sr-shortcuts>disabled</sr-shortcuts>
                                                                </config-items>
                                                                <policy-name>POLICY_R7</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH_R7</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH_R7</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>strict-spf</destination-algorithm>
                                                                        <policy-name>POLICY_R7_STRICT</policy-name>
                                                                        <destination>100.7.7.7</destination>
                                                                        <admin-state>disabled</admin-state>
                                                                        <sr-shortcuts>enabled</sr-shortcuts>
                                                                </config-items>
                                                                <policy-name>POLICY_R7_STRICT</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH_64235</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH_64235</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>spf</destination-algorithm>
                                                                        <policy-name>POLICY_R40</policy-name>
                                                                        <destination>100.40.40.40</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                </config-items>
                                                                <policy-name>POLICY_R40</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH5</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH5</path-name>
                                                                                        <priority>1</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>spf</destination-algorithm>
                                                                        <policy-name>POLICY_R50</policy-name>
                                                                        <destination>100.50.50.50</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                </config-items>
                                                                <policy-name>POLICY_R50</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>P2-R3-R8-R4</path-name>
                                                                                <config-items>
                                                                                        <path-name>P2-R3-R8-R4</path-name>
                                                                                        <priority>1</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>spf</destination-algorithm>
                                                                        <policy-name>R3</policy-name>
                                                                        <destination>100.3.3.3</destination>
                                                                        <admin-state>enabled</admin-state>
                                                                        <sr-shortcuts>enabled</sr-shortcuts>
                                                                        <administrative-distance>100</administrative-distance>
                                                                </config-items>
                                                                <policy-name>R3</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH1</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH1</path-name>
                                                                                        <priority>5</priority>
                                                                                </config-items>
                                                                        </path>
                                                                        <path>
                                                                                <path-name>PATH3</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH3</path-name>
                                                                                        <priority>4</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                        <policy>
                                                                <config-items>
                                                                        <destination-algorithm>spf</destination-algorithm>
                                                                        <policy-name>R3_2</policy-name>
                                                                        <destination>100.3.3.3</destination>
                                                                        <admin-state>disabled</admin-state>
                                                                        <sr-shortcuts>enabled</sr-shortcuts>
                                                                </config-items>
                                                                <policy-name>R3_2</policy-name>
                                                                <paths>
                                                                        <path>
                                                                                <path-name>PATH2</path-name>
                                                                                <config-items>
                                                                                        <path-name>PATH2</path-name>
                                                                                        <priority>10</priority>
                                                                                </config-items>
                                                                        </path>
                                                                </paths>
                                                        </policy>
                                                </policies>
                                                <paths>
                                                        <path>
                                                                <config-items>
                                                                        <name>P2-R3-R8-R4</name>
                                                                </config-items>
                                                                <name>P2-R3-R8-R4</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.2.2.2</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.3.3.3</include-ipv4-address>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>8</include-index>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.4.4.4</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH1</name>
                                                                </config-items>
                                                                <name>PATH1</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <label>16001</label>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH2</name>
                                                                </config-items>
                                                                <name>PATH2</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>6</include-index>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>2</include-index>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>3</include-index>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>7</include-index>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <include-index>8</include-index>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH3</name>
                                                                </config-items>
                                                                <name>PATH3</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.4.4.4</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.3.3.3</include-ipv4-address>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.2.2.2</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH5</name>
                                                                </config-items>
                                                                <name>PATH5</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_64235</name>
                                                                </config-items>
                                                                <name>PATH_64235</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.4.4.4</include-ipv4-address>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.2.2.2</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.3.3.3</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.5.5.5</include-ipv4-address>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_R1</name>
                                                                </config-items>
                                                                <name>PATH_R1</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.5.5.5</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_R4</name>
                                                                </config-items>
                                                                <name>PATH_R4</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.1.1.1</include-ipv4-address>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.5.5.5</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_R5</name>
                                                                </config-items>
                                                                <name>PATH_R5</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.1.1.1</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>2</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.4.4.4</include-ipv4-address>
                                                                                                        <hop-id>2</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.1.1.1</include-ipv4-address>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_R6</name>
                                                                </config-items>
                                                                <name>PATH_R6</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.1.1.1</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.5.5.5</include-ipv4-address>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>2</sl-id>
                                                                                </config-items>
                                                                                <sl-id>2</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>PATH_R7</name>
                                                                </config-items>
                                                                <name>PATH_R7</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>4</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.1.1.1</include-ipv4-address>
                                                                                                        <hop-id>4</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>5</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>strict-spf</algorithm>
                                                                                                        <include-ipv4-address>100.4.4.4</include-ipv4-address>
                                                                                                        <hop-id>5</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                        <path>
                                                                <config-items>
                                                                        <name>R7_R6</name>
                                                                </config-items>
                                                                <name>R7_R6</name>
                                                                <segment-lists>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.7.7.7</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                        <hop>
                                                                                                <hop-id>3</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>3</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>1</sl-id>
                                                                                </config-items>
                                                                                <sl-id>1</sl-id>
                                                                        </segment-list>
                                                                        <segment-list>
                                                                                <hops>
                                                                                        <hop>
                                                                                                <hop-id>1</hop-id>
                                                                                                <config-items>
                                                                                                        <algorithm>spf</algorithm>
                                                                                                        <include-ipv4-address>100.6.6.6</include-ipv4-address>
                                                                                                        <hop-id>1</hop-id>
                                                                                                </config-items>
                                                                                        </hop>
                                                                                </hops>
                                                                                <config-items>
                                                                                        <sl-id>2</sl-id>
                                                                                </config-items>
                                                                                <sl-id>2</sl-id>
                                                                        </segment-list>
                                                                </segment-lists>
                                                        </path>
                                                </paths>
                                        </mpls>
                                </dn-segment-routing:segment-routing>
                        </dn-protocol:protocols>
                </drivenets-top>
    </config>
"""